/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Banking;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Stark
 */
public class ChangePass extends javax.swing.JFrame {

String Old_Pass,New_Pass,ReNewPass,Username,NewUsername;
char[] a;
int i;
ConnectMe conMe=new ConnectMe();
String sel,update,update2;
ResultSet rs;
String OldPassDb;

    public ChangePass() {
        initComponents();
    }
        public ChangePass(String u) {
        initComponents();
        Username=u;
        txt_Uname.setText(u);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_Submit = new javax.swing.JButton();
        btn_Cancle = new javax.swing.JButton();
        txt_OldPass = new javax.swing.JPasswordField();
        txt_NewPass = new javax.swing.JPasswordField();
        txt_ReNewPass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_Uname = new javax.swing.JTextField();
        chkbx_Tick = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Change Password");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("Old Password");

        jLabel2.setFont(jLabel1.getFont());
        jLabel2.setText("New Password");

        jLabel3.setFont(jLabel1.getFont());
        jLabel3.setText("Retype Password");

        btn_Submit.setFont(jLabel1.getFont());
        btn_Submit.setText("Submit");
        btn_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SubmitActionPerformed(evt);
            }
        });

        btn_Cancle.setFont(jLabel1.getFont());
        btn_Cancle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back-icon.png"))); // NOI18N
        btn_Cancle.setText("Back");
        btn_Cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancleActionPerformed(evt);
            }
        });

        txt_OldPass.setFont(jLabel1.getFont());

        txt_NewPass.setFont(jLabel1.getFont());

        txt_ReNewPass.setFont(jLabel1.getFont());

        jLabel4.setFont(new java.awt.Font("Narkisim", 0, 30)); // NOI18N
        jLabel4.setText("Change Password");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("Username");

        txt_Uname.setEditable(false);
        txt_Uname.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        chkbx_Tick.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        chkbx_Tick.setText("Check to change Username");
        chkbx_Tick.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkbx_TickItemStateChanged(evt);
            }
        });
        chkbx_Tick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbx_TickActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FAQ-icon.png"))); // NOI18N
        jLabel6.setToolTipText("The changes will reflect when you restart the app");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(chkbx_Tick, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_OldPass, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(txt_NewPass)
                            .addComponent(txt_ReNewPass)
                            .addComponent(txt_Uname)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Cancle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(chkbx_Tick)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_OldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_NewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ReNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(45, 45, 45)
                .addComponent(btn_Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btn_Cancle)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SubmitActionPerformed
        a=txt_OldPass.getPassword();
        Old_Pass=new String(a);
        a=txt_NewPass.getPassword();
        New_Pass=new String(a);
        a=txt_ReNewPass.getPassword();
        ReNewPass=new String(a);
        NewUsername=txt_Uname.getText();
        
        sel="SELECT * FROM Login WHERE Username='"+Username+"' AND Password='"+Old_Pass+"'";
        update="UPDATE Login set Password = '" + New_Pass +"' where Username = '" + Username + "' ";
        update2="UPDATE Login set Password = '" + New_Pass +"', Username='"+NewUsername+"' where Username = '" + Username + "' ";
        
        if (Old_Pass.equals("")||New_Pass.equals("")||ReNewPass.equals("")||NewUsername.equals("")) 
        {
        JOptionPane.showMessageDialog(null,"Please Enter Every Field", "Error occured",
					JOptionPane.INFORMATION_MESSAGE);    
        }
        else if(Old_Pass.equalsIgnoreCase(New_Pass))
        {
            JOptionPane.showMessageDialog(null,"You entered same Password Again", "Error occured",
					JOptionPane.INFORMATION_MESSAGE);
            txt_NewPass.setText("");
            txt_ReNewPass.setText("");
            txt_NewPass.requestFocus();
        }
        else if(!(New_Pass.equals(ReNewPass)))
        {
        JOptionPane.showMessageDialog(null,"Sorry Both Passwords do not match", "Error occured",
					JOptionPane.INFORMATION_MESSAGE);
                txt_NewPass.setText("");
                txt_ReNewPass.setText("");
                txt_NewPass.requestFocus();
        }
        else
        {
            rs=conMe.getConnection(sel);
            
            try {
                boolean b=rs.next();
                OldPassDb=rs.getString("Password");    

                if (Old_Pass.equalsIgnoreCase(OldPassDb))    
                {
                    if(chkbx_Tick.isSelected())
                    {
                    i=conMe.UpdateInsertDeleteQuerry(update2);
                    }
                    else
                    {
                    i=conMe.UpdateInsertDeleteQuerry(update);
                    }
                    
                    if(i==1)
                    {
                    JOptionPane.showMessageDialog(null,"Password Change Sucessfull!!!", "Congratulations",
					JOptionPane.INFORMATION_MESSAGE);
                txt_NewPass.setText("");
                txt_ReNewPass.setText("");
                txt_OldPass.setText("");
                txt_OldPass.requestFocus();
                    }
                    else
                    {JOptionPane.showMessageDialog(null,"Nothing Changed", "Error",
					JOptionPane.INFORMATION_MESSAGE);}
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Wrong Password try again", "Error occured",
					JOptionPane.INFORMATION_MESSAGE);
                    txt_OldPass.setText("");
                    txt_OldPass.requestFocus();
                }
            } 
            catch (SQLException ex) 
            {
                JOptionPane.showMessageDialog(null,"Sql Exception Occured", "Exception Occured occured",
					JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_SubmitActionPerformed

    private void btn_CancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancleActionPerformed
        dispose();
    }//GEN-LAST:event_btn_CancleActionPerformed

    private void chkbx_TickItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkbx_TickItemStateChanged
        if (chkbx_Tick.isSelected()) 
        {
        txt_Uname.setEditable(true);    
        } else {
            txt_Uname.setEditable(false);    
        }
    }//GEN-LAST:event_chkbx_TickItemStateChanged

    private void chkbx_TickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbx_TickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkbx_TickActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePass().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancle;
    private javax.swing.JButton btn_Submit;
    private javax.swing.JCheckBox chkbx_Tick;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txt_NewPass;
    private javax.swing.JPasswordField txt_OldPass;
    private javax.swing.JPasswordField txt_ReNewPass;
    private javax.swing.JTextField txt_Uname;
    // End of variables declaration//GEN-END:variables
}
