/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Banking;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Stark
 */
public class ChequeDetails extends javax.swing.JFrame {

    int SenderAccountNumbedr=0,Accno=0;
    String ChequeNo,Date,BankName,CurrentDate;
    
    Deposit dep;
    Date d=new Date();
    Date current=new Date();
    DateFormat df=new SimpleDateFormat("dd/MM/yyyy");    
    ConnectMe conMe=new ConnectMe();
    
    public ChequeDetails() {
        initComponents();
    }
    public ChequeDetails(int A,Deposit d) {
        initComponents();
        Accno=A;
        txt_Accno.setText(""+A);
        dep=d;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_Save = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_SenderAccountNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_BankName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_ChqNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Accno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jdp_Date = new org.jdesktop.swingx.JXDatePicker();
        btn_Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Narkisim", 0, 30)); // NOI18N
        jLabel1.setText("Cheque Details");

        btn_Save.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn_Save.setText("Save");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("Account Number :");

        txt_SenderAccountNumber.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txt_SenderAccountNumber.setText("0");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("Account Number :");

        txt_BankName.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("Enter Date :");

        txt_ChqNo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Cheque Number :");

        txt_Accno.setEditable(false);
        txt_Accno.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txt_Accno.setText("0");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("Bank Name :");

        jdp_Date.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        btn_Cancel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn_Cancel.setText("Cancel");
        btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdp_Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_BankName)
                            .addComponent(txt_ChqNo)
                            .addComponent(txt_SenderAccountNumber)
                            .addComponent(txt_Accno)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(119, 119, 119))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Accno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_ChqNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jdp_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_BankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_SenderAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
       getAllText();
       String ins="insert into chequedetails(AccountNumber,ChequeNumber,Date,BankName,SenderAccountNumber) values('"+Accno+"','"+ChequeNo+"','"+Date+"','"+BankName+"','"+SenderAccountNumbedr+"')"; 
       boolean chkdt=checkDate();
       if (Accno==0|ChequeNo.equals("")|BankName.equals("")|SenderAccountNumbedr==0) 
        {
         JOptionPane.showMessageDialog(null, "Please Enter the date given on Cheque.","Error!!",JOptionPane.ERROR_MESSAGE);   
        } 
        else if(SenderAccountNumbedr==Accno)
        {
        JOptionPane.showMessageDialog(null, "Please Enter account Number given on the cheque./nYou must enter the person's Account number who gave you the cheque.","Error!!",JOptionPane.ERROR_MESSAGE);
        }
        else if(chkdt==false)
        {
        JOptionPane.showMessageDialog(null, "You cannot enter checque prior to date given on the cheque..","Error!!",JOptionPane.ERROR_MESSAGE);
        dispose();
        dep.reset();
        }
       else
        {
           int a=conMe.UpdateInsertDeleteQuerry(ins);
            if (a==1) 
            {
                JOptionPane.showMessageDialog(null, "Cheque Details Entered successfully","Success!!",JOptionPane.INFORMATION_MESSAGE); 
                dispose();
                dep.ChequeNo=ChequeNo;
            } 
            else 
            {
                 JOptionPane.showMessageDialog(null, "Something went wrong.","Error!!",JOptionPane.ERROR_MESSAGE); 
                 dispose();
                 dep.reset();
            }
        }
    }//GEN-LAST:event_btn_SaveActionPerformed

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed
        dispose();
        dep.reset();
    }//GEN-LAST:event_btn_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChequeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChequeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChequeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChequeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChequeDetails().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_Save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private org.jdesktop.swingx.JXDatePicker jdp_Date;
    private javax.swing.JTextField txt_Accno;
    private javax.swing.JTextField txt_BankName;
    private javax.swing.JTextField txt_ChqNo;
    private javax.swing.JTextField txt_SenderAccountNumber;
    // End of variables declaration//GEN-END:variables

    private void getAllText() {
        ChequeNo=txt_ChqNo.getText();
        d=jdp_Date.getDate();
        if(d!=null)
        {
        Date=df.format(d);
        }
        else{JOptionPane.showMessageDialog(null, "Please Enter the date given on Cheque.");}
        CurrentDate=df.format(current);
        BankName=txt_BankName.getText();
    try{SenderAccountNumbedr=Integer.parseInt(txt_SenderAccountNumber.getText());}catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Please Enter a vlid Account Number.\nAccount number must be a number.");}
    }

    private boolean checkDate()
    {
    boolean b=false;
    Date d1,d2;
    int a;
        try {
            d1=df.parse(CurrentDate);
            d2=df.parse(Date);
            a=d1.compareTo(d2);
            if (a>=0){ b=true; } 
            } catch (ParseException ex) {
            Logger.getLogger(ChequeDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    return b;
    }
}