/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Banking;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Stark
 */
public class FDForm extends javax.swing.JFrame {

    String[] m={"Self","Child"};
    
    ConnectMe conMe=new ConnectMe();
    DefaultComboBoxModel<String> model=new DefaultComboBoxModel<>();
    DefaultComboBoxModel<String> model1=new DefaultComboBoxModel<>(m);
    Date d=new Date();
    DateFormat df=new SimpleDateFormat("dd/MM/yyyy");
    ResultSet rs;    
    String Mode="Self",CurrentDate;
    int Accno=0,Amount=0,Period=0,Interest=0,FDNumber;
    double TotalAmount=0;
    
    
    public FDForm() {
        initComponents();
        fillData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Date = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcmb_Mode = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txt_Amount = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_Period = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_Interest = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jcmb_Accno = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txt_TotalAmount = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lbl_Error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Narkisim", 0, 30)); // NOI18N
        jLabel1.setText("Fixed Deposit Form");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("Today :");

        txt_Date.setEditable(false);
        txt_Date.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("Mode :");

        jcmb_Mode.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jcmb_Mode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("Amount in Rupees :");

        txt_Amount.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txt_Amount.setText("0");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("Period in years :");

        txt_Period.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txt_Period.setText("0");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Total Amount :");

        txt_Interest.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txt_Interest.setText("0");

        jButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jcmb_Accno.setEditable(true);
        jcmb_Accno.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jcmb_Accno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcmb_Accno.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcmb_AccnoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Enter Account Number :");

        txt_TotalAmount.setEditable(false);
        txt_TotalAmount.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txt_TotalAmount.setText("0");

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setText("Interest in Percent :");

        lbl_Error.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbl_Error.setForeground(new java.awt.Color(255, 0, 0));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(165, 165, 165))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jLabel2)
                        .add(18, 18, 18)
                        .add(txt_Date, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 102, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(25, 25, 25))))
            .add(jPanel1Layout.createSequentialGroup()
                .add(179, 179, 179)
                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 137, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(24, 24, 24)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(jLabel3)
                        .add(18, 18, 18)
                        .add(jcmb_Accno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 196, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(jLabel5)
                            .add(jLabel6)
                            .add(jLabel7)
                            .add(jLabel9))
                        .add(57, 57, 57)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jcmb_Mode, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(txt_Amount)
                            .add(txt_Period)
                            .add(txt_Interest)
                            .add(txt_TotalAmount))))
                .add(77, 77, 77))
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(lbl_Error, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jLabel1)
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(txt_Date, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(36, 36, 36)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jcmb_Accno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(43, 43, 43)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jcmb_Mode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(43, 43, 43)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(txt_Amount, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(43, 43, 43)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(txt_Period, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(43, 43, 43)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txt_Interest, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel9))
                .add(43, 43, 43)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txt_TotalAmount, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7))
                .add(18, 18, 18)
                .add(lbl_Error, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcmb_AccnoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcmb_AccnoPopupMenuWillBecomeInvisible

    }//GEN-LAST:event_jcmb_AccnoPopupMenuWillBecomeInvisible

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      getAllText();
        if (Accno==0|Amount==0|Period==0|Interest==0|Mode.equals("")|TotalAmount==0) 
        {
             JOptionPane.showMessageDialog(null, "Please enter all details..", "Error", JOptionPane.ERROR_MESSAGE);
        } 
        else if(Period>100)
        {
        JOptionPane.showMessageDialog(null, "Fixed Deposit Not allowed for more than 100 years.", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(Interest>20)
        {
        JOptionPane.showMessageDialog(null, "Interest cannot be more than 20%", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        else 
        {
            String ins="insert into fixeddeposit values('"+FDNumber+"','"+Accno+"','"+Mode+"','"+Amount+"','"+Period+"','"+Interest+"','"+CurrentDate+"','"+TotalAmount+"')";
            int a=conMe.UpdateInsertDeleteQuerry(ins);
            if (a==1) 
            {
            JOptionPane.showMessageDialog(null, "Fixed Deposit Updated Successfully.", "Error", JOptionPane.INFORMATION_MESSAGE); 
            clearAll();
            } 
            else 
            {
            JOptionPane.showMessageDialog(null, "Something Went Wrong in Deposit Form.", "Error", JOptionPane.ERROR_MESSAGE); 
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FDForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FDForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FDForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FDForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FDForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jcmb_Accno;
    private javax.swing.JComboBox jcmb_Mode;
    private javax.swing.JLabel lbl_Error;
    private javax.swing.JTextField txt_Amount;
    private javax.swing.JTextField txt_Date;
    private javax.swing.JTextField txt_Interest;
    private javax.swing.JTextField txt_Period;
    private javax.swing.JTextField txt_TotalAmount;
    // End of variables declaration//GEN-END:variables

    private void fillData() 
    {
        txt_Interest.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                lbl_Error.setText("");
                calculate();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                lbl_Error.setText("");
                 calculate();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                
            }

            private void calculate() {
              try{
                  Amount=Integer.parseInt(txt_Amount.getText());
                  Interest=Integer.parseInt(txt_Interest.getText());
                  Period=Integer.parseInt(txt_Period.getText());
                  double SI=Amount*Interest*Period/100;
                  TotalAmount=SI+Amount;
                  txt_TotalAmount.setText(""+TotalAmount);
                          }
              catch(NumberFormatException ex)
              {lbl_Error.setText("Please Enter Proper Numbers..");
              }
            }
        });
        String sele="select AccountNumber from customerinfo";
         rs=conMe.getConnection(sele);
        try {
            while(rs.next())
            {
            String s=""+rs.getInt("AccountNumber");
            model.addElement(s);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Deposit.class.getName()).log(Level.SEVERE, null, ex);
        }
        jcmb_Accno.setModel(model);
        AutoCompleteDecorator.decorate(jcmb_Accno);
        jcmb_Mode.setModel(model1);
        AutoCompleteDecorator.decorate(jcmb_Mode);
        
        CurrentDate=df.format(d);
        txt_Date.setText(CurrentDate);
    }

    private void getAllText()
    {
  try{ try{ Accno=Integer.parseInt((String)jcmb_Accno.getSelectedItem());
        Mode=jcmb_Mode.getSelectedItem().toString();
        Amount=Integer.parseInt(txt_Amount.getText());
        Period=Integer.parseInt(txt_Period.getText());
        Interest=Integer.parseInt(txt_Interest.getText());
        TotalAmount=Double.parseDouble(txt_TotalAmount.getText());
        }catch(NumberFormatException ex)
        {JOptionPane.showMessageDialog(null, "Please enter a valid Numbers.", "Error", JOptionPane.ERROR_MESSAGE); }
        getCurrentFDNumber();
        }catch(IllegalArgumentException ex){}
    }

    private void getCurrentFDNumber() {
       String sel="select FDNumber from fixeddeposit";
        try
        {
        rs=conMe.getConnection(sel);
            if (rs.last()) {
        FDNumber=rs.getInt("FDNumber")+1;
        }
            else
            {
            FDNumber=1;
            }
        }
        catch(SQLException ex)
    {
     JOptionPane.showMessageDialog(null,"Sql Exception Occured", "Exception occured",
               JOptionPane.INFORMATION_MESSAGE);
          ex.printStackTrace();
    }
    }

    private void clearAll() {
       txt_Amount.setText("0");
       txt_Interest.setText("0");
       Mode="Self";
       txt_Period.setText("0");
       jcmb_Accno.setSelectedIndex(0);
    }
}
