/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Banking;

import javax.swing.JOptionPane;

/**
 *
 * @author Stark
 */
public class MainForm extends javax.swing.JFrame {

    String user,access;
    
    
    public MainForm() {
        initComponents();
    }
        public MainForm(String u,String a) 
        {
        initComponents();
        user=u;
        access=a;
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnu_Application = new javax.swing.JMenu();
        mnuitm_Logout = new javax.swing.JMenuItem();
        mnuitm_Exit = new javax.swing.JMenuItem();
        mnu_Account = new javax.swing.JMenu();
        mnuitm_NewAccount = new javax.swing.JMenuItem();
        mnuitm_SearchUpdate = new javax.swing.JMenuItem();
        mnuitm_AllCustomers = new javax.swing.JMenuItem();
        mnu_Transactions = new javax.swing.JMenu();
        mnuitm_Deposit = new javax.swing.JMenuItem();
        mnuitm_Withdraw = new javax.swing.JMenuItem();
        mnuitm_Transfer = new javax.swing.JMenuItem();
        mnuitm_FdForm = new javax.swing.JMenuItem();
        mnuitm_DraftForm = new javax.swing.JMenuItem();
        mnu_Viedw = new javax.swing.JMenu();
        mnuitm_BalanceSheet = new javax.swing.JMenuItem();
        mnuitm_FDs = new javax.swing.JMenuItem();
        mnuitm_Drafts = new javax.swing.JMenuItem();
        mnu_Setting = new javax.swing.JMenu();
        mnu_ChangePass = new javax.swing.JMenuItem();
        mnu_AddUser = new javax.swing.JMenuItem();
        mnu_DeleteUser = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.jpg"))); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(78, 40));

        mnu_Application.setText("Application");
        mnu_Application.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mnuitm_Logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mnuitm_Logout.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mnuitm_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Log-Out-icon.png"))); // NOI18N
        mnuitm_Logout.setText("Logout");
        mnuitm_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitm_LogoutActionPerformed(evt);
            }
        });
        mnu_Application.add(mnuitm_Logout);

        mnuitm_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mnuitm_Exit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mnuitm_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Apps-session-logout-icon.png"))); // NOI18N
        mnuitm_Exit.setText("Exit");
        mnuitm_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitm_ExitActionPerformed(evt);
            }
        });
        mnu_Application.add(mnuitm_Exit);

        jMenuBar1.add(mnu_Application);

        mnu_Account.setText("Account");
        mnu_Account.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mnuitm_NewAccount.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mnuitm_NewAccount.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mnuitm_NewAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Actions-list-add-user-icon.png"))); // NOI18N
        mnuitm_NewAccount.setText("New Account");
        mnuitm_NewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitm_NewAccountActionPerformed(evt);
            }
        });
        mnu_Account.add(mnuitm_NewAccount);

        mnuitm_SearchUpdate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuitm_SearchUpdate.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mnuitm_SearchUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search-icon.png"))); // NOI18N
        mnuitm_SearchUpdate.setText("Search/Update Account");
        mnuitm_SearchUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitm_SearchUpdateActionPerformed(evt);
            }
        });
        mnu_Account.add(mnuitm_SearchUpdate);

        mnuitm_AllCustomers.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuitm_AllCustomers.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mnuitm_AllCustomers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Programming-Show-Property-icon.png"))); // NOI18N
        mnuitm_AllCustomers.setText("All Customers");
        mnuitm_AllCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitm_AllCustomersActionPerformed(evt);
            }
        });
        mnu_Account.add(mnuitm_AllCustomers);

        jMenuBar1.add(mnu_Account);

        mnu_Transactions.setText("Transactions");
        mnu_Transactions.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mnuitm_Deposit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        mnuitm_Deposit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mnuitm_Deposit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/safe-icon.png"))); // NOI18N
        mnuitm_Deposit.setText("Deposit");
        mnuitm_Deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitm_DepositActionPerformed(evt);
            }
        });
        mnu_Transactions.add(mnuitm_Deposit);

        mnuitm_Withdraw.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        mnuitm_Withdraw.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mnuitm_Withdraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Money-icon.png"))); // NOI18N
        mnuitm_Withdraw.setText("Withdraw");
        mnuitm_Withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitm_WithdrawActionPerformed(evt);
            }
        });
        mnu_Transactions.add(mnuitm_Withdraw);

        mnuitm_Transfer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        mnuitm_Transfer.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mnuitm_Transfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wire-transfer-icon.png"))); // NOI18N
        mnuitm_Transfer.setText("Transfer");
        mnuitm_Transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitm_TransferActionPerformed(evt);
            }
        });
        mnu_Transactions.add(mnuitm_Transfer);

        mnuitm_FdForm.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        mnuitm_FdForm.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mnuitm_FdForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/forms-icon.png"))); // NOI18N
        mnuitm_FdForm.setText("FD Form");
        mnuitm_FdForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitm_FdFormActionPerformed(evt);
            }
        });
        mnu_Transactions.add(mnuitm_FdForm);

        mnuitm_DraftForm.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuitm_DraftForm.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mnuitm_DraftForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/invoice-icon.png"))); // NOI18N
        mnuitm_DraftForm.setText("Draft Form");
        mnuitm_DraftForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitm_DraftFormActionPerformed(evt);
            }
        });
        mnu_Transactions.add(mnuitm_DraftForm);

        jMenuBar1.add(mnu_Transactions);

        mnu_Viedw.setText("View");
        mnu_Viedw.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mnuitm_BalanceSheet.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuitm_BalanceSheet.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mnuitm_BalanceSheet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/account-icon.png"))); // NOI18N
        mnuitm_BalanceSheet.setText("Account Details");
        mnuitm_BalanceSheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitm_BalanceSheetActionPerformed(evt);
            }
        });
        mnu_Viedw.add(mnuitm_BalanceSheet);

        mnuitm_FDs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuitm_FDs.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mnuitm_FDs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/forms-icon.png"))); // NOI18N
        mnuitm_FDs.setText("FD's");
        mnuitm_FDs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitm_FDsActionPerformed(evt);
            }
        });
        mnu_Viedw.add(mnuitm_FDs);

        mnuitm_Drafts.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuitm_Drafts.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mnuitm_Drafts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/invoice-icon.png"))); // NOI18N
        mnuitm_Drafts.setText("Draft's");
        mnuitm_Drafts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitm_DraftsActionPerformed(evt);
            }
        });
        mnu_Viedw.add(mnuitm_Drafts);

        jMenuBar1.add(mnu_Viedw);

        mnu_Setting.setText("Settings");
        mnu_Setting.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnu_Setting.setMaximumSize(new java.awt.Dimension(80, 32767));

        mnu_ChangePass.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnu_ChangePass.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mnu_ChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Gear-icon.png"))); // NOI18N
        mnu_ChangePass.setText("Change Password");
        mnu_ChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_ChangePassActionPerformed(evt);
            }
        });
        mnu_Setting.add(mnu_ChangePass);

        mnu_AddUser.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mnu_AddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Office-Customer-Male-Light-icon.png"))); // NOI18N
        mnu_AddUser.setText("Create User");
        mnu_AddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_AddUserActionPerformed(evt);
            }
        });
        mnu_Setting.add(mnu_AddUser);

        mnu_DeleteUser.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mnu_DeleteUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Actions-list-remove-user-icon.png"))); // NOI18N
        mnu_DeleteUser.setText("Delete User");
        mnu_DeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_DeleteUserActionPerformed(evt);
            }
        });
        mnu_Setting.add(mnu_DeleteUser);

        jMenuBar1.add(mnu_Setting);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnu_ChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_ChangePassActionPerformed
        ChangePass p=new ChangePass(user);
        p.setVisible(true);
        p.requestFocus();
    }//GEN-LAST:event_mnu_ChangePassActionPerformed

    private void mnu_AddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_AddUserActionPerformed
        if (access.equals("A"))
        {
            CreateUser csp=new CreateUser();
            csp.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Sorry you must login as admin to add a user.", "Exception occured",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mnu_AddUserActionPerformed

    private void mnu_DeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_DeleteUserActionPerformed
        if (access.equals("A"))
        {
            DeleteUser du=new DeleteUser();
            du.setVisible(true);
            du.requestFocus();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Sorry login in as an admin user to delete user.", "Exception occured",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mnu_DeleteUserActionPerformed

    private void mnuitm_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitm_LogoutActionPerformed
       Login log=new Login();
       log.setVisible(true);
       dispose();
    }//GEN-LAST:event_mnuitm_LogoutActionPerformed

    private void mnuitm_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitm_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuitm_ExitActionPerformed

    private void mnuitm_FdFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitm_FdFormActionPerformed
        FDForm fd=new FDForm();
        fd.setVisible(true);
        fd.requestFocusInWindow();
    }//GEN-LAST:event_mnuitm_FdFormActionPerformed

    private void mnuitm_TransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitm_TransferActionPerformed
        Transfer tf=new Transfer();
        tf.setVisible(true);
        tf.requestFocusInWindow();
    }//GEN-LAST:event_mnuitm_TransferActionPerformed

    private void mnuitm_AllCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitm_AllCustomersActionPerformed
       AllCustomers al=new AllCustomers();
       al.setVisible(true);
       al.requestFocusInWindow();
    }//GEN-LAST:event_mnuitm_AllCustomersActionPerformed

    private void mnuitm_DepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitm_DepositActionPerformed
       Deposit dep=new Deposit();
       dep.setVisible(true);
       dep.requestFocusInWindow();
    }//GEN-LAST:event_mnuitm_DepositActionPerformed

    private void mnuitm_WithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitm_WithdrawActionPerformed
       Widthdraw wd=new Widthdraw();
       wd.setVisible(true);
       wd.requestFocusInWindow();
    }//GEN-LAST:event_mnuitm_WithdrawActionPerformed

    private void mnuitm_DraftFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitm_DraftFormActionPerformed
        DraftForm df=new DraftForm();
        df.setVisible(true);
        df.requestFocusInWindow();
    }//GEN-LAST:event_mnuitm_DraftFormActionPerformed

    private void mnuitm_BalanceSheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitm_BalanceSheetActionPerformed
       BalanceSheet bal=new BalanceSheet();
       bal.setVisible(true);
       bal.requestFocusInWindow();
    }//GEN-LAST:event_mnuitm_BalanceSheetActionPerformed

    private void mnuitm_FDsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitm_FDsActionPerformed
        ViewFdForms vfd=new ViewFdForms();
        vfd.setVisible(true);
        vfd.requestFocusInWindow();
    }//GEN-LAST:event_mnuitm_FDsActionPerformed

    private void mnuitm_DraftsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitm_DraftsActionPerformed
       ViewDrafts vd=new ViewDrafts();
       vd.setVisible(true);
       vd.requestFocusInWindow();
    }//GEN-LAST:event_mnuitm_DraftsActionPerformed

    private void mnuitm_NewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitm_NewAccountActionPerformed
        NewAccount Ac=new NewAccount();
        Ac.setVisible(true);
        Ac.requestFocusInWindow();
    }//GEN-LAST:event_mnuitm_NewAccountActionPerformed

    private void mnuitm_SearchUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitm_SearchUpdateActionPerformed
        SearchUpdateAccount sua=new SearchUpdateAccount();
        sua.setVisible(true);
        sua.requestFocusInWindow();
    }//GEN-LAST:event_mnuitm_SearchUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnu_Account;
    private javax.swing.JMenuItem mnu_AddUser;
    private javax.swing.JMenu mnu_Application;
    private javax.swing.JMenuItem mnu_ChangePass;
    private javax.swing.JMenuItem mnu_DeleteUser;
    private javax.swing.JMenu mnu_Setting;
    private javax.swing.JMenu mnu_Transactions;
    private javax.swing.JMenu mnu_Viedw;
    private javax.swing.JMenuItem mnuitm_AllCustomers;
    private javax.swing.JMenuItem mnuitm_BalanceSheet;
    private javax.swing.JMenuItem mnuitm_Deposit;
    private javax.swing.JMenuItem mnuitm_DraftForm;
    private javax.swing.JMenuItem mnuitm_Drafts;
    private javax.swing.JMenuItem mnuitm_Exit;
    private javax.swing.JMenuItem mnuitm_FDs;
    private javax.swing.JMenuItem mnuitm_FdForm;
    private javax.swing.JMenuItem mnuitm_Logout;
    private javax.swing.JMenuItem mnuitm_NewAccount;
    private javax.swing.JMenuItem mnuitm_SearchUpdate;
    private javax.swing.JMenuItem mnuitm_Transfer;
    private javax.swing.JMenuItem mnuitm_Withdraw;
    // End of variables declaration//GEN-END:variables
}
