/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Banking;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;


public class NewAccount extends javax.swing.JFrame {

    ConnectMe conMe=new ConnectMe();
    DateFormat df= new SimpleDateFormat("dd/MM/yyyy");
    Date d=new Date();
    DefaultComboBoxModel<String> model=new DefaultComboBoxModel<>();
    JFileChooser fc=new JFileChooser();
    java.net.URL imageURL = NewAccount.class.getResource("NoImage.jpg");
    File file;
    FileInputStream fin;
    ImageIcon ico;
    RefreshMe rm=new RefreshMe();
    
    int AccNo=0,Balance=0;
    String Name,DOB="",Address,Destrict,State,Gender="",Marital="",MotherName,FatherName,CurrentDate;
    String path="";
    Double PhoneNumber=0.0;
    
    ResultSet rs;
    Connection con=conMe.getConnection();
    PreparedStatement ps;
    
    public NewAccount() {
        initComponents();
        initMyComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderGroup = new javax.swing.ButtonGroup();
        MaritalGroup = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_AccountNumber = new javax.swing.JTextField();
        txt_Name = new javax.swing.JTextField();
        DatePic_DOB = new org.jdesktop.swingx.JXDatePicker();
        txt_PhoneNumber = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtar_Address = new javax.swing.JTextArea();
        txt_Destrict = new javax.swing.JTextField();
        jcmb_State = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_FatherName = new javax.swing.JTextField();
        txt_MotherName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lbl_Pic = new javax.swing.JLabel();
        btn_UploadPic = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        radio_Male = new javax.swing.JRadioButton();
        radio_Female = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        radio_Married = new javax.swing.JRadioButton();
        radio_UnMarried = new javax.swing.JRadioButton();
        txt_Date = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_Ballance = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btn_Save = new javax.swing.JButton();
        btn_AddMore = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Account");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Narkisim", 0, 30)); // NOI18N
        jLabel1.setText("Customer Information Form");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Account Number :");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("Name :");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("Date Of Birth :");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("Phone Number :");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Address :");

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setText("Destrict :");

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setText("State :");

        txt_AccountNumber.setEditable(false);
        txt_AccountNumber.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        txt_Name.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        DatePic_DOB.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        txt_PhoneNumber.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        txtar_Address.setColumns(20);
        txtar_Address.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtar_Address.setRows(5);
        jScrollPane1.setViewportView(txtar_Address);

        txt_Destrict.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        jcmb_State.setEditable(true);
        jcmb_State.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jcmb_State.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setText("Mother's Name :");

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel13.setText("Father's Name :");

        txt_FatherName.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        txt_MotherName.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel8)
                        .add(101, 101, 101)
                        .add(txt_Destrict))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(jPanel2Layout.createSequentialGroup()
                                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabel3)
                                        .add(jLabel4)
                                        .add(jLabel5)
                                        .add(jLabel6))
                                    .add(30, 30, 30)
                                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(txt_PhoneNumber)
                                        .add(DatePic_DOB, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(txt_Name)
                                        .add(txt_AccountNumber)))
                                .add(jPanel2Layout.createSequentialGroup()
                                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabel9)
                                        .add(jLabel7))
                                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jPanel2Layout.createSequentialGroup()
                                            .add(101, 101, 101)
                                            .add(jcmb_State, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .add(jPanel2Layout.createSequentialGroup()
                                            .add(99, 99, 99)
                                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 234, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(0, 0, Short.MAX_VALUE))
                                        .add(jPanel2Layout.createSequentialGroup()
                                            .add(101, 101, 101)
                                            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                .add(txt_FatherName)
                                                .add(txt_MotherName))))))
                            .add(jLabel10)
                            .add(jLabel13))
                        .add(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(txt_AccountNumber, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(20, 20, 20)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(txt_Name, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(27, 27, 27)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(DatePic_DOB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(27, 27, 27)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(txt_PhoneNumber, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(27, 27, 27)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7))
                .add(28, 28, 28)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(txt_Destrict, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(27, 27, 27)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(jcmb_State, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(txt_MotherName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(27, 27, 27)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel13)
                    .add(txt_FatherName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(67, 67, 67))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lbl_Pic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_UploadPic.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn_UploadPic.setText("Upload Pic");
        btn_UploadPic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UploadPicActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setText("Gender :");

        radio_Male.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        radio_Male.setText("Male");
        radio_Male.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radio_MaleItemStateChanged(evt);
            }
        });

        radio_Female.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        radio_Female.setText("Female");
        radio_Female.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radio_FemaleItemStateChanged(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setText("Marital Status :");

        radio_Married.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        radio_Married.setText("Married");
        radio_Married.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radio_MarriedItemStateChanged(evt);
            }
        });

        radio_UnMarried.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        radio_UnMarried.setText("Unmarried");
        radio_UnMarried.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radio_UnMarriedItemStateChanged(evt);
            }
        });

        txt_Date.setEditable(false);
        txt_Date.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txt_Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("Today :");

        txt_Ballance.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txt_Ballance.setText("0");

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel14.setText("Balance :");

        btn_Save.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn_Save.setText("Save");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });

        btn_AddMore.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn_AddMore.setText("Add More");
        btn_AddMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddMoreActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                        .add(jLabel2)
                        .add(18, 18, 18)
                        .add(txt_Date, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 142, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(16, 16, 16))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                        .add(btn_Save, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 117, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(37, 37, 37)
                        .add(btn_AddMore, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 118, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(43, 43, 43))))
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(lbl_Pic, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 404, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(jPanel3Layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel12)
                    .add(jLabel11)
                    .add(jLabel14))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(btn_UploadPic)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel3Layout.createSequentialGroup()
                                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(radio_Male)
                                    .add(radio_Married))
                                .add(27, 27, 27)
                                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(radio_Female)
                                    .add(radio_UnMarried)))
                            .add(txt_Ballance))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(txt_Date, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(31, 31, 31)
                .add(lbl_Pic, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 288, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(btn_UploadPic)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 30, Short.MAX_VALUE)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel11)
                    .add(radio_Male)
                    .add(radio_Female))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12)
                    .add(radio_Married)
                    .add(radio_UnMarried))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel14)
                    .add(txt_Ballance, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(btn_Save, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btn_AddMore, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel1)
                .add(245, 245, 245))
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(33, 33, 33)
                .add(jLabel1)
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(42, 42, 42))
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DateActionPerformed

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
       getAllText();
      boolean b= getBalance();
        if (AccNo==0|DOB.equals("")|PhoneNumber==0.0|Address.equals("")|Destrict.equals("")|MotherName.equals("")|FatherName.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Fill all details..", "Error",
               JOptionPane.INFORMATION_MESSAGE);
        }
        else if(b==false)
        {
        JOptionPane.showMessageDialog(null,"You entered Invalid Balance", "Error",
               JOptionPane.INFORMATION_MESSAGE);
        }
        else if(Gender.equals("")|Marital.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Fill Gender and Marital Details..", "Error",
               JOptionPane.INFORMATION_MESSAGE);
        }
        
        else
        {            if (file==null) 
                      {
                        file=new File(imageURL.toString().substring(6));
                      }
                try {
                    fin=new FileInputStream(file);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(NewAccount.class.getName()).log(Level.SEVERE, null, ex);
                }
            
           String ins="insert into customerinfo values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            try {
                ps=con.prepareStatement(ins);
                ps.setInt(1, AccNo);
                ps.setString(2, Name);
                ps.setDouble(3, PhoneNumber);
                ps.setString(4, DOB);
                ps.setString(5, Address);
                ps.setString(6, Destrict);
                ps.setString(7, State);
                ps.setString(8, Gender);
                ps.setString(9, Marital);
                ps.setString(10, MotherName);
                ps.setString(11, FatherName);
                ps.setInt(12, Balance);
                ps.setBlob(13, fin);
                ps.setString(14, CurrentDate);
                
                int a=ps.executeUpdate();
                if (a==1) {
                    JOptionPane.showMessageDialog(null,"Account Details Saved Successfully", "Congratulations!!",
               JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null,"Something Went Wrong", "Error!!",
               JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(NewAccount.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       
    }//GEN-LAST:event_btn_SaveActionPerformed

    private void btn_UploadPicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UploadPicActionPerformed
       getImage();
    }//GEN-LAST:event_btn_UploadPicActionPerformed

    private void radio_MaleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radio_MaleItemStateChanged
        if (radio_Male.isSelected()) 
        {
        Gender="Male";    
        } 
    }//GEN-LAST:event_radio_MaleItemStateChanged

    private void radio_FemaleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radio_FemaleItemStateChanged
        if (radio_Female.isSelected()) 
        {
        Gender="Female";    
        } 
    }//GEN-LAST:event_radio_FemaleItemStateChanged

    private void radio_MarriedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radio_MarriedItemStateChanged
       if (radio_Married.isSelected()) 
        {
        Marital="Married";    
        } 
    }//GEN-LAST:event_radio_MarriedItemStateChanged

    private void radio_UnMarriedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radio_UnMarriedItemStateChanged
       if (radio_UnMarried.isSelected()) 
        {
        Marital="Unmarried";    
        }     
    }//GEN-LAST:event_radio_UnMarriedItemStateChanged

    private void btn_AddMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddMoreActionPerformed
        clearAll();
        rm.refreshMe(this);
        initMyComponents();
    }//GEN-LAST:event_btn_AddMoreActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewAccount().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker DatePic_DOB;
    private javax.swing.ButtonGroup GenderGroup;
    private javax.swing.ButtonGroup MaritalGroup;
    private javax.swing.JButton btn_AddMore;
    private javax.swing.JButton btn_Save;
    private javax.swing.JButton btn_UploadPic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox jcmb_State;
    private javax.swing.JLabel lbl_Pic;
    private javax.swing.JRadioButton radio_Female;
    private javax.swing.JRadioButton radio_Male;
    private javax.swing.JRadioButton radio_Married;
    private javax.swing.JRadioButton radio_UnMarried;
    private javax.swing.JTextField txt_AccountNumber;
    private javax.swing.JTextField txt_Ballance;
    private javax.swing.JTextField txt_Date;
    private javax.swing.JTextField txt_Destrict;
    private javax.swing.JTextField txt_FatherName;
    private javax.swing.JTextField txt_MotherName;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_PhoneNumber;
    private javax.swing.JTextArea txtar_Address;
    // End of variables declaration//GEN-END:variables

    private void initMyComponents() 
    {
        GenderGroup.add(radio_Male);
        GenderGroup.add(radio_Female);
        MaritalGroup.add(radio_Married);
        MaritalGroup.add(radio_UnMarried);
        CurrentDate=df.format(d);
        txt_Date.setText(CurrentDate); //Setting Current Date
        fillData();
        getCurrentAccountNumber();
        ico=new ImageIcon(imageURL);
        lbl_Pic.setIcon(ico);
    }
    private void fillData() 
    {
    String sel="select State from misc";
    
    try{
    rs=conMe.getConnection(sel);
        while (rs.next()) 
        {            
        model.addElement(rs.getString("State"));   
        }
    }
    catch(SQLException ex)
    {
     JOptionPane.showMessageDialog(null,"Sql Exception Occured", "Exception occured",
               JOptionPane.INFORMATION_MESSAGE);   
    }
        jcmb_State.setModel(model);
        AutoCompleteDecorator.decorate(jcmb_State);
    }

    private void getCurrentAccountNumber() {
        String sel="select AccountNumber from customerinfo";
        try
        {
        rs=conMe.getConnection(sel);
            if (rs.last()) {
        AccNo=rs.getInt("AccountNumber")+1;
        }
            else
            {
            AccNo=1;
            }
        }
        catch(SQLException ex)
    {
     JOptionPane.showMessageDialog(null,"Sql Exception Occured", "Exception occured",
               JOptionPane.INFORMATION_MESSAGE);
          ex.printStackTrace();
    }
        String acno=""+AccNo;
        txt_AccountNumber.setText(acno);
    }

    private void getAllText() 
    {
       Name=txt_Name.getText();
       try{ PhoneNumber=Double.parseDouble(txt_PhoneNumber.getText());}
       catch(NumberFormatException ex){ JOptionPane.showMessageDialog(null,"Please Enter Proper Number.", "Exception occured",
               JOptionPane.INFORMATION_MESSAGE);}
        Address=txtar_Address.getText();
        Destrict=txt_Destrict.getText();
        State=(String)jcmb_State.getSelectedItem();
        MotherName=txt_MotherName.getText();
        FatherName=txt_FatherName.getText(); 
        d=DatePic_DOB.getDate();
        if(d==null)
        {
            JOptionPane.showMessageDialog(null,"Please Enter Date of Birth", "Exception occured",
               JOptionPane.INFORMATION_MESSAGE);
        }
        else{
        DOB=df.format(d);
        }
    }
    private boolean getBalance()
    {
    try
    {
        Balance=Integer.parseInt(txt_Ballance.getText());
    }
    catch(NumberFormatException ex)
    {
    return false;
    }
    return true;
    }
    private void getImage() 
    {  
      fc.setFileFilter(null);
      fc.showOpenDialog(null);
      file=fc.getSelectedFile();
      if(file!=null)
      {
      path=file.getAbsolutePath();
      ico=new ImageIcon(path);
      lbl_Pic.setIcon(ico);
      }
      else
      {
        file=new File(imageURL.toString().substring(6));
      }
    }

    private void clearAll() {
        txt_AccountNumber.setText("");
        txt_Ballance.setText("0");
        txt_Destrict.setText("");
        txt_FatherName.setText("");
        txt_MotherName.setText("");
        txt_Name.setText("");
        txt_PhoneNumber.setText("");
        txtar_Address.setText("");
        Gender="";
        Marital="";
        lbl_Pic.setIcon(null);
        radio_Male.setSelected(false);        
        radio_Female.setSelected(false);        
        radio_UnMarried.setSelected(false);        
        radio_Married.setSelected(false);
        d=new Date();
        txt_Date.setText("");
        DatePic_DOB.setDate(null);
        jcmb_State.setSelectedIndex(0);
     } 
    public void Dispose()
    {
    dispose();
    }
}