/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Banking;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Stark
 */
public class SearchUpdateAccount extends javax.swing.JFrame {

    ConnectMe conMe=new ConnectMe();
    DateFormat df= new SimpleDateFormat("dd/MM/yyyy");
    Date d=new Date();
    DefaultComboBoxModel<String> model=new DefaultComboBoxModel<>();
    DefaultComboBoxModel<String> model2=new DefaultComboBoxModel<>();
    DefaultComboBoxModel<String> model3=new DefaultComboBoxModel<>();
    JFileChooser fc=new JFileChooser();
    java.net.URL imageURL = NewAccount.class.getResource("NoImage.jpg");
    File file;
    FileInputStream fin;
    ImageIcon ico;
    RefreshMe rm=new RefreshMe();
    
    int AccNo=0,Balance=0;
    String Name,DOB="",PhoneNumber,Address,Destrict,State,Gender="",Marital="",MotherName,FatherName,CurrentDate;
    String path="";
    
     int ACCOUNT_NUMBER=1,NAME=2;
    
    ResultSet rs,rs2,rs3;
    Connection con=conMe.getConnection();
    PreparedStatement ps;
    public SearchUpdateAccount() {
        initComponents();
        initMyComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderGroup = new javax.swing.ButtonGroup();
        MaritalGroup = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        DatePic_DOB = new org.jdesktop.swingx.JXDatePicker();
        txt_PhoneNumber = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtar_Address = new javax.swing.JTextArea();
        txt_Destrict = new javax.swing.JTextField();
        jcmb_State = new javax.swing.JComboBox();
        txt_MotherName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_FatherName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jcmb_AccNo = new javax.swing.JComboBox();
        jcmb_Name = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        lbl_Pic = new javax.swing.JLabel();
        btn_UploadPic = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        radio_Male = new javax.swing.JRadioButton();
        radio_Female = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        radio_Married = new javax.swing.JRadioButton();
        radio_UnMarried = new javax.swing.JRadioButton();
        txt_Ballance = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btn_Update = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        txt_Date = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update Form");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Narkisim", 0, 30)); // NOI18N
        jLabel1.setText("Update Form");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Account Number :");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("Name :");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("Date Of Birth :");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("Phone Number :");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Address :");

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setText("Destrict :");

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setText("State :");

        DatePic_DOB.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        txt_PhoneNumber.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        txtar_Address.setColumns(20);
        txtar_Address.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtar_Address.setRows(5);
        jScrollPane1.setViewportView(txtar_Address);

        txt_Destrict.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        jcmb_State.setEditable(true);
        jcmb_State.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jcmb_State.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txt_MotherName.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setText("Mother's Name :");

        txt_FatherName.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel13.setText("Father's Name :");

        jcmb_AccNo.setEditable(true);
        jcmb_AccNo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jcmb_AccNo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcmb_AccNo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcmb_AccNoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jcmb_Name.setEditable(true);
        jcmb_Name.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jcmb_Name.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcmb_Name.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcmb_NamePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel8)
                        .add(101, 101, 101)
                        .add(txt_Destrict))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel3)
                                    .add(jLabel4)
                                    .add(jLabel5)
                                    .add(jLabel6))
                                .add(30, 30, 30)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(txt_PhoneNumber)
                                    .add(DatePic_DOB, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jcmb_AccNo, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jcmb_Name, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel9)
                                    .add(jLabel7))
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel2Layout.createSequentialGroup()
                                        .add(99, 99, 99)
                                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 234, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(0, 0, Short.MAX_VALUE))
                                    .add(jPanel2Layout.createSequentialGroup()
                                        .add(101, 101, 101)
                                        .add(jcmb_State, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel10)
                            .add(jLabel13))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(txt_FatherName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .add(txt_MotherName))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(33, 33, 33)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jcmb_AccNo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(26, 26, 26)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jcmb_Name, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(DatePic_DOB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(27, 27, 27)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(txt_PhoneNumber, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(27, 27, 27)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7))
                .add(28, 28, 28)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(txt_Destrict, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(27, 27, 27)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(jcmb_State, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(txt_MotherName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(27, 27, 27)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel13)
                    .add(txt_FatherName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lbl_Pic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_UploadPic.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn_UploadPic.setText("Upload Pic");
        btn_UploadPic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UploadPicActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setText("Gender :");

        radio_Male.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        radio_Male.setText("Male");
        radio_Male.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radio_MaleItemStateChanged(evt);
            }
        });

        radio_Female.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        radio_Female.setText("Female");
        radio_Female.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radio_FemaleItemStateChanged(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setText("Marital Status :");

        radio_Married.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        radio_Married.setText("Married");
        radio_Married.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radio_MarriedItemStateChanged(evt);
            }
        });

        radio_UnMarried.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        radio_UnMarried.setText("Unmarried");
        radio_UnMarried.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radio_UnMarriedItemStateChanged(evt);
            }
        });

        txt_Ballance.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel14.setText("Balance :");

        btn_Update.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn_Update.setText("Update");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });

        btn_Delete.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn_Delete.setText("Delete");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lbl_Pic, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 416, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel3Layout.createSequentialGroup()
                                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(radio_Married)
                                    .add(jPanel3Layout.createSequentialGroup()
                                        .add(jLabel11)
                                        .add(50, 50, 50)))
                                .add(37, 37, 37)
                                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(radio_Female)
                                    .add(radio_UnMarried)))
                            .add(jLabel12)
                            .add(jPanel3Layout.createSequentialGroup()
                                .add(jLabel14)
                                .add(18, 18, 18)
                                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel3Layout.createSequentialGroup()
                                        .add(btn_Update, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(58, 58, 58)
                                        .add(btn_Delete, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(txt_Ballance, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 206, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(40, 40, 40)
                        .add(radio_Male))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(180, 180, 180)
                        .add(btn_UploadPic)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(lbl_Pic, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 216, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(btn_UploadPic)
                .add(4, 4, 4)
                .add(jLabel11)
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(radio_Male)
                    .add(radio_Female))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 27, Short.MAX_VALUE)
                .add(jLabel12)
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(radio_Married)
                    .add(radio_UnMarried))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txt_Ballance, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel14))
                .add(34, 34, 34)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btn_Update, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btn_Delete, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(3, 3, 3))
        );

        txt_Date.setEditable(false);
        txt_Date.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txt_Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("Date Of Creation :");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(302, 302, 302)
                .add(jLabel1)
                .addContainerGap(445, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jLabel2)
                        .add(18, 18, 18)
                        .add(txt_Date, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 142, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(26, 26, 26)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 23, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(txt_Date, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane2.setViewportView(jPanel1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DateActionPerformed
        
    }//GEN-LAST:event_txt_DateActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        getAllText();
         boolean b= getBalance();
         if (AccNo==0|DOB.equals("")|PhoneNumber.equals("")|Address.equals("")|Destrict.equals("")|MotherName.equals("")|FatherName.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Fill all details..", "Error",
               JOptionPane.INFORMATION_MESSAGE);
        }
        else if(b==false)
        {
        JOptionPane.showMessageDialog(null,"You entered Invalid Balance", "Error",
               JOptionPane.INFORMATION_MESSAGE);
        }
        else if(Gender.equals("")|Marital.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Fill Gender and Marital Details..", "Error",
               JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            if (file==null) 
            {
            file=new File(imageURL.toString().substring(6));    
            }
        try {
            
                 fin=new FileInputStream(file);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(NewAccount.class.getName()).log(Level.SEVERE, null, ex);
                    fin=null;
                }
          
        String update="update customerinfo set Name=?,PhoneNumber=?,DOB=?,Address=?,District=?,State=?,Gender=?,MaritalStatus=?,MotherName=?,FatherName=?,Balance=?,Image=? where AccountNumber=?";
            
            try {
                ps=con.prepareStatement(update);
                ps.setString(1, Name);
                ps.setString(2, PhoneNumber);
                ps.setString(3, DOB);
                ps.setString(4, Address);
                ps.setString(5, Destrict);
                ps.setString(6, State);
                ps.setString(7, Gender);
                ps.setString(8, Marital);
                ps.setString(9, MotherName);
                ps.setString(10, FatherName);
                ps.setInt(11, Balance);
                ps.setBlob(12, fin);
                ps.setInt(13, AccNo);
                
                int a=ps.executeUpdate();
                if (a==1) {
                    JOptionPane.showMessageDialog(null,"Account Details Updated Successfully", "Congratulations!!",
               JOptionPane.INFORMATION_MESSAGE);
                            clearAll();
                            initMyComponents();
                } else {
                    JOptionPane.showMessageDialog(null,"Something Went Wrong", "Error!!",
               JOptionPane.INFORMATION_MESSAGE);
                }
            }
            catch(SQLException ex){ Logger.getLogger(NewAccount.class.getName()).log(Level.SEVERE, null, ex);}
        }
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void jcmb_AccNoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcmb_AccNoPopupMenuWillBecomeInvisible
     try{  try{ AccNo=Integer.parseInt((String)jcmb_AccNo.getSelectedItem()); }
       catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Please Enter a Valid Account Number. \nUse Our Autocompletion feature.");}
       
        String sele="select * from customerinfo where AccountNumber='"+AccNo+"'";
        fillData(sele,ACCOUNT_NUMBER);
     }catch(IllegalArgumentException ex){}
    }//GEN-LAST:event_jcmb_AccNoPopupMenuWillBecomeInvisible

    private void jcmb_NamePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcmb_NamePopupMenuWillBecomeInvisible
       try{ Name=(String)jcmb_Name.getSelectedItem();
        
        String sele="select * from customerinfo where Name='"+Name+"'";
        fillData(sele, NAME);
        }catch(IllegalArgumentException ex){}
    }//GEN-LAST:event_jcmb_NamePopupMenuWillBecomeInvisible

    private void radio_MaleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radio_MaleItemStateChanged
       if (radio_Male.isSelected()) 
        {
        Gender="Male";    
        } 
    }//GEN-LAST:event_radio_MaleItemStateChanged

    private void radio_FemaleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radio_FemaleItemStateChanged
        if (radio_Female.isSelected()) 
        {
        Gender="Female";    
        } 
    }//GEN-LAST:event_radio_FemaleItemStateChanged

    private void radio_MarriedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radio_MarriedItemStateChanged
      if (radio_Married.isSelected()) 
        {
        Marital="Married";    
        } 
    }//GEN-LAST:event_radio_MarriedItemStateChanged

    private void radio_UnMarriedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radio_UnMarriedItemStateChanged
        if (radio_UnMarried.isSelected()) 
        {
        Marital="Unmarried";    
        }   
    }//GEN-LAST:event_radio_UnMarriedItemStateChanged

    private void btn_UploadPicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UploadPicActionPerformed
        getImage();
    }//GEN-LAST:event_btn_UploadPicActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
      Object[] options = {"Yes, I know", "Oops!"};
int m = JOptionPane.showOptionDialog(null,
                "Your about to delete an account..",
                "Caution!!",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);
if(m==JOptionPane.YES_OPTION)
{
AccNo=Integer.parseInt((String)jcmb_AccNo.getSelectedItem());
String dele="delete from customerinfo where AccountNumber=?";
            try {
                ps=con.prepareStatement(dele);
                ps.setInt(1,AccNo);
               int a= ps.executeUpdate();
                if (a==1) 
                {
                  JOptionPane.showMessageDialog(null,"Account Deleted Succesfully", "Congratulations",
               JOptionPane.INFORMATION_MESSAGE);  
                  clearAll();
                  rm.refreshMe(this);
                  initMyComponents();
                } else {
                    JOptionPane.showMessageDialog(null,"Nothing Deleted.\nSomething Went Wrong", "Congratulations",
               JOptionPane.INFORMATION_MESSAGE); 
                }
            } catch (SQLException ex) {
                Logger.getLogger(SearchUpdateAccount.class.getName()).log(Level.SEVERE, null, ex);
            }
}        
    }//GEN-LAST:event_btn_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchUpdateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchUpdateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchUpdateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchUpdateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchUpdateAccount().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker DatePic_DOB;
    private javax.swing.ButtonGroup GenderGroup;
    private javax.swing.ButtonGroup MaritalGroup;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Update;
    private javax.swing.JButton btn_UploadPic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox jcmb_AccNo;
    private javax.swing.JComboBox jcmb_Name;
    private javax.swing.JComboBox jcmb_State;
    private javax.swing.JLabel lbl_Pic;
    private javax.swing.JRadioButton radio_Female;
    private javax.swing.JRadioButton radio_Male;
    private javax.swing.JRadioButton radio_Married;
    private javax.swing.JRadioButton radio_UnMarried;
    private javax.swing.JTextField txt_Ballance;
    private javax.swing.JTextField txt_Date;
    private javax.swing.JTextField txt_Destrict;
    private javax.swing.JTextField txt_FatherName;
    private javax.swing.JTextField txt_MotherName;
    private javax.swing.JTextField txt_PhoneNumber;
    private javax.swing.JTextArea txtar_Address;
    // End of variables declaration//GEN-END:variables
 private void initMyComponents() 
    {
        GenderGroup.add(radio_Male);
        GenderGroup.add(radio_Female);
        MaritalGroup.add(radio_Married);
        MaritalGroup.add(radio_UnMarried);
        CurrentDate=df.format(d);
        txt_Date.setText(CurrentDate); //Setting Current Date
        fillData();
        java.net.URL imageURL = NewAccount.class.getResource("NoImage.jpg");
        ico=new ImageIcon(imageURL);
        lbl_Pic.setIcon(ico);
    }
 private void fillData() 
    {
    String sel="select State from misc";
    String sel2="select AccountNumber from customerinfo";
    String sele3="select Name from customerinfo";
    try{
    rs=conMe.getConnection(sel);
    rs2=conMe.getConnection(sel2);
    rs3=conMe.getConnection(sele3);
        while (rs.next()) 
        {            
        model.addElement(rs.getString("State"));   
        }
        while (rs2.next()) 
        {            
        String s=""+rs2.getInt("AccountNumber");
        model2.addElement(s);
        }
        while (rs3.next()) 
        {            
        model3.addElement(rs3.getString("Name"));
        }
    }
    catch(SQLException ex)
    {
     JOptionPane.showMessageDialog(null,"Sql Exception Occured", "Exception occured",
               JOptionPane.INFORMATION_MESSAGE);  
     ex.printStackTrace();
    }
        jcmb_State.setModel(model);
        AutoCompleteDecorator.decorate(jcmb_State);
        jcmb_AccNo.setModel(model2);
        AutoCompleteDecorator.decorate(jcmb_AccNo);
        jcmb_Name.setModel(model3);
        AutoCompleteDecorator.decorate(jcmb_Name);
    }
 
     private void fillData(String q,int a)
    {
    rs=conMe.getConnection(q);
    switch(a)
    {
      case 1:
        try {
            if(rs.next())
            {
              String s=rs.getString("Name");
              jcmb_Name.setSelectedItem(s);
              fillAll(rs);
            }
            else
            {
             JOptionPane.showMessageDialog(null,"No Account Number Found.", "Exception occured",
               JOptionPane.INFORMATION_MESSAGE);   
            }
        } catch (SQLException | ParseException ex) {
            Logger.getLogger(SearchUpdateAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
       break;
          
      case 2:
                   try {
            if(rs.next())
            {
              String s=""+rs.getInt("AccountNumber");
              jcmb_AccNo.setSelectedItem(s);
              fillAll(rs);
            }
            else
            {
             JOptionPane.showMessageDialog(null,"No Name Found.", "Exception occured",
               JOptionPane.INFORMATION_MESSAGE);   
            }
        } catch (SQLException | ParseException ex) {
            Logger.getLogger(SearchUpdateAccount.class.getName()).log(Level.SEVERE, null, ex);
        }  
      
      break;
       }        
    }

    private void fillAll(ResultSet rs) throws SQLException, ParseException 
    {
       Date _d=df.parse(rs.getString("DOB"));
       DatePic_DOB.setDate(_d);
       txt_PhoneNumber.setText(rs.getString("PhoneNumber"));
       txtar_Address.setText(rs.getString("Address"));
       txt_Destrict.setText(rs.getString("District"));
       jcmb_State.setSelectedItem(rs.getString("State"));
       txt_MotherName.setText(rs.getString("MotherName"));
       txt_FatherName.setText(rs.getString("FatherName"));
       txt_Ballance.setText(""+rs.getInt("Balance"));
       txt_Date.setText(rs.getString("DateOfAccountCreation")); 
       
       String s=rs.getString("Gender");
        if (s.equals("Male")) {
         radio_Male.setSelected(true);            
        } else {
            radio_Female.setSelected(true);
        }
        s=rs.getString("MaritalStatus");
        if (s.equals("Married")) {
            radio_Married.setSelected(true);
        } else {
            radio_UnMarried.setSelected(true);
        }
       
       byte[] bytes=rs.getBytes("Image");
       if(bytes!=null)
       {
       Image image=getToolkit().createImage(bytes);
       ImageIcon _ico=new ImageIcon(image);
       lbl_Pic.setIcon(_ico);
       }
       else
       {
       java.net.URL imageURL = SearchUpdateAccount.class.getResource("NoImage.jpg");
      ImageIcon _ico=new ImageIcon(imageURL);
       lbl_Pic.setIcon(_ico);
       }
    
    }


        private void getAllText() 
       {
        Name=(String)jcmb_Name.getSelectedItem();
    try{AccNo=Integer.parseInt((String)jcmb_AccNo.getSelectedItem());}catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Sorry There are No accounts..");}
        PhoneNumber=txt_PhoneNumber.getText();
        Address=txtar_Address.getText();
        Destrict=txt_Destrict.getText();
        State=(String)jcmb_State.getSelectedItem();
        MotherName=txt_MotherName.getText();
        FatherName=txt_FatherName.getText(); 
        d=DatePic_DOB.getDate();
        if(d==null)
        {
            JOptionPane.showMessageDialog(null,"Please Enter Date of Birth", "Exception occured",
               JOptionPane.INFORMATION_MESSAGE);
        }
        else{
        DOB=df.format(d);
        }
       }

    private boolean getBalance() 
    {
    try
    {
        Balance=Integer.parseInt(txt_Ballance.getText());
    }
    catch(NumberFormatException ex)
    {
    return false;
    }
    return true;
    }
    
    private void getImage() 
    {  
      fc.setFileFilter(null);
      fc.showOpenDialog(null);
      file=fc.getSelectedFile();
       if(file!=null)
      {
      path=file.getAbsolutePath();
      ico=new ImageIcon(path);
      lbl_Pic.setIcon(ico);
      }
      else
      {
        file=new File(imageURL.toString().substring(6));
      }
    }

    private void clearAll() {
        txt_Ballance.setText("0");
        txt_Destrict.setText("");
        txt_FatherName.setText("");
        txt_MotherName.setText("");
        txt_PhoneNumber.setText("");
        txtar_Address.setText("");
        Gender="";
        Marital="";
        lbl_Pic.setIcon(null);
        radio_Male.setSelected(false);        
        radio_Female.setSelected(false);        
        radio_UnMarried.setSelected(false);        
        radio_Married.setSelected(false);  
        txt_Date.setText("");
        DatePic_DOB.setDate(null);
    }
    public void Dispose()
    {
    dispose();
    }
}
