/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Banking;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Stark
 */
public class Transfer extends javax.swing.JFrame {


    Date d1=new Date();
    DateFormat df=new SimpleDateFormat("dd/MM/yyyy");
    DefaultComboBoxModel<String> model=new DefaultComboBoxModel<>();
    DefaultComboBoxModel<String> model1=new DefaultComboBoxModel<>();
    ConnectMe conMe=new ConnectMe();
    ResultSet rs;
    
    String CurrentDate,Name,Mode;
    int OldBalance=0,Amount=0,AccnoFrom=0,AccnoTo=0,FinalBalanceFrom,FinalBalanceTo=0,OldBalanceTo=-1;
    
    
    public Transfer() {
        initComponents();
        fillData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Date = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcmb_AccnoFrom = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcmb_AccnoTo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txt_Amount = new javax.swing.JTextField();
        txt_Name = new javax.swing.JTextField();
        txt_OldBal = new javax.swing.JTextField();
        btn_Transfer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Narkisim", 0, 30)); // NOI18N
        jLabel1.setText("Transfer Form");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("Date :");

        txt_Date.setEditable(false);
        txt_Date.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("From Account Number :");

        jcmb_AccnoFrom.setEditable(true);
        jcmb_AccnoFrom.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jcmb_AccnoFrom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcmb_AccnoFrom.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcmb_AccnoFromPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("Name :");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("Current Amount :");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("Destination Account :");

        jcmb_AccnoTo.setEditable(true);
        jcmb_AccnoTo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jcmb_AccnoTo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcmb_AccnoTo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcmb_AccnoToPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Amount :");

        txt_Amount.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txt_Amount.setText("0");

        txt_Name.setEditable(false);
        txt_Name.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        txt_OldBal.setEditable(false);
        txt_OldBal.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txt_OldBal.setText("0");

        btn_Transfer.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn_Transfer.setText("Transfer");
        btn_Transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TransferActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(29, 29, 29)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel4)
                                    .add(jLabel3)
                                    .add(jLabel5)
                                    .add(jLabel6)
                                    .add(jLabel7))
                                .add(18, 18, 18)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jcmb_AccnoTo, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, txt_OldBal)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, txt_Name)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jcmb_AccnoFrom, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(txt_Amount, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 188, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(176, 176, 176)
                                .add(btn_Transfer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(0, 26, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jLabel2)
                        .add(18, 18, 18)
                        .add(txt_Date, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 116, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .add(jPanel1Layout.createSequentialGroup()
                .add(125, 125, 125)
                .add(jLabel1)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(jLabel1)
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(txt_Date, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(42, 42, 42)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jcmb_AccnoFrom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(txt_Name, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(txt_OldBal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(jcmb_AccnoTo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(txt_Amount, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(btn_Transfer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcmb_AccnoFromPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcmb_AccnoFromPopupMenuWillBecomeInvisible
       try{ try{AccnoFrom=Integer.parseInt((String)jcmb_AccnoFrom.getSelectedItem());}
        catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Please Enter Valid Account Number...");}
        String sele="select Name,Balance from customerinfo where AccountNumber='"+AccnoFrom+"'";
        rs=conMe.getConnection(sele);
            try {
                if(rs.next())
                {
                 txt_Name.setText(rs.getString("Name"));
                 txt_OldBal.setText(""+rs.getString("Balance"));
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Account Number not present...");
                }
            } catch (SQLException ex1) {
                Logger.getLogger(Widthdraw.class.getName()).log(Level.SEVERE, null, ex1);
            }
       }catch(IllegalArgumentException ex){}
    }//GEN-LAST:event_jcmb_AccnoFromPopupMenuWillBecomeInvisible

    private void btn_TransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TransferActionPerformed
      getAllText();
      getFinalBalance();
        
        String insf="insert into balancesheet(Date,AccountNumber,Mode,Debit,Balance) values('"+CurrentDate+"','"+AccnoFrom+"','"+Mode+"','"+Amount+"','"+FinalBalanceFrom+"')";
        String inst="insert into balancesheet(Date,AccountNumber,Mode,Deposit,Balance) values('"+CurrentDate+"','"+AccnoTo+"','"+Mode+"','"+Amount+"','"+FinalBalanceTo+"')";
        if (Name.equals("")) 
        {
        JOptionPane.showMessageDialog(null, "Please select an account number from Drop Down list...","Error!!",JOptionPane.ERROR_MESSAGE);    
        } 
        else if(OldBalanceTo==-1)
        {
        JOptionPane.showMessageDialog(null, "Please select Destination Account from the Drop Down List","Error!!",JOptionPane.ERROR_MESSAGE);
        }
        else if(Amount==0) 
        {
        JOptionPane.showMessageDialog(null, "Please enter Amount","Error!!",JOptionPane.ERROR_MESSAGE);      
        }
        else if(Amount>OldBalance)
        {
        JOptionPane.showMessageDialog(null, "You cant Transfer more money than your account has..","Error!!",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
        int a=conMe.UpdateInsertDeleteQuerry(insf);
        int b=conMe.UpdateInsertDeleteQuerry(inst);
            if (a==1&b==1) 
            {
                updateAccountBalance();
                JOptionPane.showMessageDialog(null, "Debited Successfully.", "Error", JOptionPane.INFORMATION_MESSAGE); 
                clearAll();
            } 
            else 
            {
            JOptionPane.showMessageDialog(null, "Something Went Wrong in Deposit Form.", "Error", JOptionPane.ERROR_MESSAGE); 
            } 
        
        }
    }//GEN-LAST:event_btn_TransferActionPerformed

    private void jcmb_AccnoToPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcmb_AccnoToPopupMenuWillBecomeInvisible
    try{  try{AccnoTo=Integer.parseInt((String)jcmb_AccnoTo.getSelectedItem());}
        catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Please Enter Valid Account Number...");}
        String sele="select Balance from customerinfo where AccountNumber='"+AccnoTo+"'";
        rs=conMe.getConnection(sele);
            try {
                if(rs.next())
                {
                OldBalanceTo=Integer.parseInt(rs.getString("Balance"));
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Account Number not present...");
                }
            } catch (SQLException ex1) {
                Logger.getLogger(Widthdraw.class.getName()).log(Level.SEVERE, null, ex1);
            }
            }catch(IllegalArgumentException ex){}
    }//GEN-LAST:event_jcmb_AccnoToPopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transfer().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Transfer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jcmb_AccnoFrom;
    private javax.swing.JComboBox jcmb_AccnoTo;
    private javax.swing.JTextField txt_Amount;
    private javax.swing.JTextField txt_Date;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_OldBal;
    // End of variables declaration//GEN-END:variables

    private void fillData() 
    {

    CurrentDate=df.format(d1);
    txt_Date.setText(CurrentDate);
    
    String sele="select AccountNumber from customerinfo";
    rs=conMe.getConnection(sele);
        try {
            while(rs.next())
            {
                model.addElement(""+rs.getInt("AccountNumber"));
                model1.addElement(""+rs.getInt("AccountNumber"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Widthdraw.class.getName()).log(Level.SEVERE, null, ex);
        }
        jcmb_AccnoFrom.setModel(model);
        AutoCompleteDecorator.decorate(jcmb_AccnoFrom);
        jcmb_AccnoTo.setModel(model1);
        AutoCompleteDecorator.decorate(jcmb_AccnoTo);
    }
    
    private void getAllText() 
    {
    CurrentDate=txt_Date.getText();
    Name=txt_Name.getText();
    Mode="Transfer";
    OldBalance=Integer.parseInt(txt_OldBal.getText());
    try{Amount=Integer.parseInt(txt_Amount.getText());}
    catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Amount is not vaild\nPlease enter a valid amount...");}
    try{AccnoTo=Integer.parseInt((String)jcmb_AccnoTo.getSelectedItem());}
    catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Please Enter Valid Account Number.", "Error", JOptionPane.ERROR_MESSAGE);}
    }

    private void getFinalBalance() {
        try{Amount=Integer.parseInt(txt_Amount.getText());}
        catch(NumberFormatException ex)
        {
        JOptionPane.showMessageDialog(null, "Please Enter Valid Amount.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        OldBalance=Integer.parseInt(txt_OldBal.getText());
        FinalBalanceFrom=OldBalance-Amount;
        FinalBalanceTo=OldBalanceTo+Amount;
    }
    private void updateAccountBalance() 
    {
       String updf="update customerinfo set Balance='"+FinalBalanceFrom+"' where AccountNumber='"+AccnoFrom+"'";
       conMe.UpdateInsertDeleteQuerry(updf);
       String updt="update customerinfo set Balance='"+FinalBalanceTo+"' where AccountNumber='"+AccnoTo+"'";
       conMe.UpdateInsertDeleteQuerry(updt);
    }
    
    private void clearAll() 
    {
       txt_Name.setText("");
       txt_OldBal.setText("0");
       txt_Amount.setText("0");
    }
}
