/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Banking;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Stark
 */
public class Widthdraw extends javax.swing.JFrame {


    Date d1=new Date();
    DateFormat df=new SimpleDateFormat("dd/MM/yyyy");
    DefaultComboBoxModel<String> model=new DefaultComboBoxModel<>();
    ConnectMe conMe=new ConnectMe();
    ResultSet rs;
    
    String CurrentDate,Name,Mode;
    int OldBalance=0,Amount=0,Accno=0,FinalBalance;
    public Widthdraw() {
        initComponents();
        fillData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Date = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcmb_Accno = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_Amount = new javax.swing.JTextField();
        txt_Name = new javax.swing.JTextField();
        txt_OldBal = new javax.swing.JTextField();
        btn_Update = new javax.swing.JButton();
        txt_Mode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Debit Form");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Narkisim", 0, 30)); // NOI18N
        jLabel1.setText("Withdraw Form");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("Date :");

        txt_Date.setEditable(false);
        txt_Date.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Enter Account Number :");

        jcmb_Accno.setEditable(true);
        jcmb_Accno.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jcmb_Accno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcmb_Accno.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcmb_AccnoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("Name :");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("Old Balance :");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("Mode :");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Debit Amount :");

        txt_Amount.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txt_Amount.setText("0");

        txt_Name.setEditable(false);
        txt_Name.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        txt_OldBal.setEditable(false);
        txt_OldBal.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txt_OldBal.setText("0");

        btn_Update.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btn_Update.setText("Update");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });

        txt_Mode.setEditable(false);
        txt_Mode.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txt_Mode.setText("Cash");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(jLabel2)
                .add(18, 18, 18)
                .add(txt_Date, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 116, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(23, 23, 23))
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(jLabel3)
                            .add(jLabel5)
                            .add(jLabel6)
                            .add(jLabel7))
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, txt_OldBal)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, txt_Name)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jcmb_Accno, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, txt_Amount, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, txt_Mode)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(158, 158, 158)
                        .add(jLabel1))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(190, 190, 190)
                        .add(btn_Update, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(jLabel1)
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(txt_Date, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(42, 42, 42)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jcmb_Accno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(txt_Name, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(txt_OldBal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(33, 33, 33)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(txt_Mode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(33, 33, 33)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(txt_Amount, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(btn_Update, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        getAllText();
        getFinalBalance();
        String ins="insert into balancesheet(Date,AccountNumber,Mode,Debit,Balance) values('"+CurrentDate+"','"+Accno+"','"+Mode+"','"+Amount+"','"+FinalBalance+"')";
        if (Name.equals("")) 
        {
        JOptionPane.showMessageDialog(null, "Please select an account number from Drop Down list...","Error!!",JOptionPane.ERROR_MESSAGE);    
        } 
        else if(Amount==0) 
        {
        JOptionPane.showMessageDialog(null, "Please enter Amount","Error!!",JOptionPane.ERROR_MESSAGE);      
        }
        else if(Amount>OldBalance)
        {
        JOptionPane.showMessageDialog(null, "you cant debit more money than your account has..","Error!!",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
           int a=conMe.UpdateInsertDeleteQuerry(ins);
            if (a==1) 
            {
                updateAccountBalance();
                JOptionPane.showMessageDialog(null, "Debited Successfully.", "Error", JOptionPane.INFORMATION_MESSAGE); 
                clearAll();
            } 
            else 
            {
            JOptionPane.showMessageDialog(null, "Something Went Wrong in Deposit Form.", "Error", JOptionPane.ERROR_MESSAGE); 
            } 
        }
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void jcmb_AccnoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcmb_AccnoPopupMenuWillBecomeInvisible
      try{  try{Accno=Integer.parseInt((String)jcmb_Accno.getSelectedItem());}
        catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Please Enter Valid Account Number...");}
        String sele="select Name,Balance from customerinfo where AccountNumber='"+Accno+"'";
        rs=conMe.getConnection(sele);
            try {
                if(rs.next())
                {
                 txt_Name.setText(rs.getString("Name"));
                 txt_OldBal.setText(""+rs.getString("Balance"));
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Account Number not present...");
                }
            } catch (SQLException ex1) {
                Logger.getLogger(Widthdraw.class.getName()).log(Level.SEVERE, null, ex1);
            }
            }catch(IllegalArgumentException ex){}
        
    }//GEN-LAST:event_jcmb_AccnoPopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Widthdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Widthdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Widthdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Widthdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Widthdraw().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jcmb_Accno;
    private javax.swing.JTextField txt_Amount;
    private javax.swing.JTextField txt_Date;
    private javax.swing.JTextField txt_Mode;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_OldBal;
    // End of variables declaration//GEN-END:variables

    private void fillData() 
    {
    CurrentDate=df.format(d1);
    txt_Date.setText(CurrentDate);
    
    String sele="select AccountNumber from customerinfo";
    rs=conMe.getConnection(sele);
        try {
            while(rs.next())
            {
                model.addElement(""+rs.getInt("AccountNumber"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Widthdraw.class.getName()).log(Level.SEVERE, null, ex);
        }
        jcmb_Accno.setModel(model);
        AutoCompleteDecorator.decorate(jcmb_Accno);
    }

    private void getAllText() 
    {
    CurrentDate=txt_Date.getText();
    Name=txt_Name.getText();
    Mode=txt_Mode.getText();
    OldBalance=Integer.parseInt(txt_OldBal.getText());
    try{Amount=Integer.parseInt(txt_Amount.getText());}
    catch(NumberFormatException ex){JOptionPane.showMessageDialog(null, "Amount is not vaild\nPlease enter a valid amount...");}
    }

    private void getFinalBalance() {
        try{Amount=Integer.parseInt(txt_Amount.getText());}
        catch(NumberFormatException ex)
        {
        JOptionPane.showMessageDialog(null, "Please Enter Valid Amount.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        OldBalance=Integer.parseInt(txt_OldBal.getText());
        FinalBalance=OldBalance-Amount;
    }
    private void updateAccountBalance() 
    {
       String upd="update customerinfo set Balance='"+FinalBalance+"' where AccountNumber='"+Accno+"'";
       conMe.UpdateInsertDeleteQuerry(upd);
    }

    private void clearAll() 
    {
       txt_Name.setText("");
       txt_OldBal.setText("0");
       Mode="";
       txt_Amount.setText("0");
    }
}
